s390/kasan: adapt disabled_wait usage to avoid build error
Fix the following build error when the kernel is built with CONFIG_KASAN
broken since commit b8cec63a8a9a ("s390: simplify disabled_wait"):

arch/s390/mm/kasan_init.c: In function 'kasan_early_panic':
arch/s390/mm/kasan_init.c:31:2: error: too many arguments to function
'disabled_wait'
   31 |  disabled_wait(0);

Fixes: b8cec63a8a9a ("s390: simplify disabled_wait")
Reported-by: Benjamin Block <bblock@linux.ibm.com>
Signed-off-by: Vasily Gorbik <gor@linux.ibm.com>
Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>