PM / devfreq: Export tracepoint symbols
The following tracepoints were added to include/trace/events/power.h
but not exported:

  ERROR: "__tracepoint_memlat_dev_update" [drivers/devfreq/governor_memlat.ko]
  ERROR: "__tracepoint_memlat_dev_meas" [drivers/devfreq/governor_memlat.ko]
  ERROR: "__tracepoint_cache_hwmon_update" [drivers/devfreq/governor_cache_hwmon.ko]
  ERROR: "__tracepoint_cache_hwmon_meas" [drivers/devfreq/governor_cache_hwmon.ko]
  ERROR: "__tracepoint_bw_hwmon_update" [drivers/devfreq/governor_bw_hwmon.ko]
  ERROR: "__tracepoint_bw_hwmon_meas" [drivers/devfreq/governor_bw_hwmon.ko]

Change-Id: Ic0dedbadbee6533cba9ae312ab764873ab72a342
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>