Revert "usb: mtu3: fix up undefined reference to usb_debug_root"
It's not needed after [1] is applied, because usb_debug_root is created
by usb common core but not usbcore now.

[1] f43d89121e93 ("USB: move usb debugfs directory creation to the usb common core")

Signed-off-by: Chunfeng Yun <chunfeng.yun@mediatek.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>