DLKM: build error on user build
build error:
ERROR: "power_supply_notifier" [../../motorola/kernel/modules/
drivers/power/mmi-smbcharger-iio/mmi-smbcharger-iio.ko] undefined!
ERROR: "power_supply_class" [../../motorola/kernel/modules/
drivers/power/mmi-smbcharger-iio/mmi-smbcharger-iio.ko] undefined!
ERROR: "class_for_each_device" [../../motorola/kernel/modules/
drivers/power/mmi-smbcharger-iio/mmi-smbcharger-iio.ko] undefined!
ERROR: "kernel_power_off" [../../motorola/kernel/modules/
drivers/power/mmi-smbcharger-iio/mmi-smbcharger-iio.ko] undefined!
ERROR: "alarm_try_to_cancel" [../../motorola/kernel/modules/
drivers/power/mmi-smbcharger-iio/mmi-smbcharger-iio.ko] undefined!

They are defined in boot.img, but they don't defined in google gki.
so we should fix it as below:
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/../../kernel/
msm-$(MODULE_KERNEL_VERSION)/Module.symvers

Change-Id: Iabb4297c3c2a01a2ff57d0e11b61a973eb058184
Signed-off-by: mahj8 <mahj8@mt.com>
Reviewed-on: https://gerrit.mot.com/1791885
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Minghui Wei <weimh1@motorola.com>
Reviewed-by: Huosheng Liao <liaohs@motorola.com>
Submit-Approved: Jira Key