Revert "net: dccp: initialize (addr,port) listening hashtable"
This reverts commit 7e3f195a77c5e7f1c29d784ab102bf4950467a10.

Cause build failures when DCCP is modular.

ERROR: "inet_hashinfo2_init" [net/dccp/dccp.ko] undefined!

Signed-off-by: David S. Miller <davem@davemloft.net>